channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.1.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.3.2
  - scipy==1.15.2
name: mlflow-env
